shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 7.0
controller_patience: 5.0
conservative_reset_dist: 0.3
planner_frequency: 0.05
oscillation_timeout: 5.0
oscillation_distance: 0.1

